### ISSUE TITLE
Can not use with GTK

### ISSUE THREAD

**Issue by whizsid** [ostrosco/device_query#18] opened 2020-04-09 21:11 UTC
I have tried with some basic GTK window. I am getting a `Segmentation fault (core dumped)` error. 

Operating system: Linux

```rust
extern crate gtk;
extern crate device_query;

use device_query::{DeviceState};
use gtk::prelude::*;

fn main(){
    if let Err(_) = gtk::init() {
        panic!("UIError");
    }

    let window = gtk::Window::new(gtk::WindowType::Toplevel);
    window.set_title("First GTK+ Program");
    window.set_border_width(10);
    window.set_position(gtk::WindowPosition::Center);
    window.set_default_size(350, 70);
    let button = gtk::Button::new_with_label("Click me!");
    window.add(&button);

    let device_state = DeviceState::new();

    window.show_all();
    gtk::main();
}
```

## Dependencies
```
device_query = "0.2.3"
gtk = "0.8.1"
```

**Comment by ostrosco** [comment] 2020-04-10 04:14
Thanks for the report. I'm just starting to look into this. Could you give a bit more info about your Linux install? Are you using X11 or Wayland?

**Comment by ostrosco** [comment] 2020-04-10 04:23
I'm running Fedora 31 with Wayland and I'm able to reproduce the issue. A friend running Arch on X11 was unable to reproduce the issue. It's possible this could be a Wayland compatibility issue.

A workaround I found is to initialize the `DeviceState` before you run `gtk::init()`. I'm gonna keep on digging to see exactly what's going on though.

**Comment by ostrosco** [comment] 2020-04-10 04:42
I just pushed a fix. The issue was that my library was calling XInitThreads() which it really shouldn't have been. Let me know if master fixes your issue.

**Comment by whizsid** [comment] 2020-04-10 04:46
@ostrosco Thank You for the quick reply. I am using x11. Now it is working. Thank You!

**Closed** 2020-04-10 05:44 UTC
